### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Hotte512**
info about firebase permission... for dummis like me ;-)

@Shyim can i use user-auth or public? 

user:
`{
  "rules": {
    "users": {
      "$uid": {
        ".read": "$uid === auth.uid",
        ".write": "$uid === auth.uid"
      }
    }
  }
}`

or public
`{
  "rules": {
    ".read": true,
    ".write": true
  }
}
`

### CODE REVIEW

**Comment by shyim** [comment]
It must be public I don't implemented a auth

**Comment by Hotte512** [comment]
I think that's fine! THX, so let the dummi user like me know.. (i had to search a bit)

btw. webp is working fine ;) and if u ever need something for the garden (mostly wooden stuff) u can ask me.

**Comment by shyim** [comment]
Can you add also the note that the permissions should be public ty :3

Nice to hear. If i it's stable I would create a pr to get it in the core

**Comment by Hotte512** [comment]
Now it's more detailed.

I'll check and write some more about webp later...
atm I have no issues (it's live;) but some elements throw no webp version. I'll check my template later.

**Pull request merged**
